# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summarize/v1/summarize_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'summarize/v1/summarize_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$summarize/v1/summarize_service.proto\x12\x10oni.summarize.v1\"X\n\x10SummarizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0csummary_type\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x04 \x01(\t\"\x9b\x01\n\x11SummarizeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x12\n\nword_count\x18\x02 \x01(\x05\x12\x14\n\x0csummary_type\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\x12\x12\n\nmodel_used\x18\x06 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x07 \x01(\x02\x32h\n\x10SummarizeService\x12T\n\tSummarize\x12\".oni.summarize.v1.SummarizeRequest\x1a#.oni.summarize.v1.SummarizeResponseB5\n!com.cap.commandbar.grpc.summarizeB\x0eSummarizeProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summarize.v1.summarize_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.cap.commandbar.grpc.summarizeB\016SummarizeProtoP\001'
  _globals['_SUMMARIZEREQUEST']._serialized_start=58
  _globals['_SUMMARIZEREQUEST']._serialized_end=146
  _globals['_SUMMARIZERESPONSE']._serialized_start=149
  _globals['_SUMMARIZERESPONSE']._serialized_end=304
  _globals['_SUMMARIZESERVICE']._serialized_start=306
  _globals['_SUMMARIZESERVICE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
